name: music_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  get: 4.6.5
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/IMG_0007.JPG
    - assets/images/icon_black.png
    - assets/images/icon_white.png
    